package com.paybridge.testkit;
import com.paybridge.core.error.*;
import com.paybridge.core.model.*;
import com.paybridge.spi.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;
/** Deterministic in-memory gateway for consuming-application tests. */
public final class FakePaymentGateway implements PaymentGateway { public enum Scenario { SUCCESS, DECLINED, TIMEOUT, PROVIDER_ERROR, INVALID_REQUEST } private final Scenario scenario; private final AtomicLong ids=new AtomicLong(); private final Map<String,Payment> payments=new ConcurrentHashMap<>(); private FakePaymentGateway(Scenario scenario){this.scenario=scenario;} public static Builder builder(){return new Builder();} public PaymentProvider provider(){return PaymentProvider.of("fake");} public Set<GatewayCapability> capabilities(){return Set.of(GatewayCapability.CREATE_PAYMENT,GatewayCapability.GET_PAYMENT,GatewayCapability.REFUND,GatewayCapability.PARTIAL_REFUND,GatewayCapability.CANCEL);} public Payment createPayment(PaymentRequest request){ if(scenario==Scenario.TIMEOUT) throw error(PaymentErrorCode.PROVIDER_TIMEOUT,true); if(scenario==Scenario.PROVIDER_ERROR) throw error(PaymentErrorCode.PROVIDER_UNAVAILABLE,true); if(scenario==Scenario.INVALID_REQUEST) throw error(PaymentErrorCode.INVALID_REQUEST,false); PaymentStatus status=scenario==Scenario.DECLINED?PaymentStatus.FAILED:PaymentStatus.CAPTURED; String id="fake_"+ids.incrementAndGet(); Payment p=new Payment(new PaymentReference(provider(),id),status,request.amount(),null,Instant.EPOCH,Map.of()); payments.put(id,p); return p;} public Payment getPayment(PaymentReference reference){ Payment p=payments.get(reference.value()); if(p==null) throw error(PaymentErrorCode.PAYMENT_NOT_FOUND,false); return p;} public Refund refund(RefundRequest r){return new Refund("re_"+ids.incrementAndGet(),r.paymentReference(),r.amount(),Refund.Status.SUCCEEDED);} private PaymentException error(PaymentErrorCode c,boolean retry){return new PaymentException(c,provider(),null,retry,c.name());} public static final class Builder { private Scenario scenario=Scenario.SUCCESS; public Builder scenario(Scenario value){scenario=value;return this;} public Builder createPaymentSucceeds(){return scenario(Scenario.SUCCESS);} public FakePaymentGateway build(){return new FakePaymentGateway(scenario);} } }
