package com.paybridge.core.error;
public enum PaymentErrorCode { AUTHENTICATION_FAILED, INVALID_REQUEST, PAYMENT_DECLINED, INSUFFICIENT_FUNDS, PAYMENT_NOT_FOUND, PAYMENT_ALREADY_CAPTURED, REFUND_NOT_ALLOWED, RATE_LIMITED, PROVIDER_UNAVAILABLE, PROVIDER_TIMEOUT, NETWORK_ERROR, INVALID_WEBHOOK_SIGNATURE, UNSUPPORTED_OPERATION, UNKNOWN_PROVIDER_ERROR }
