package com.paybridge.bkash;

import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.ObjectNode;
import com.paybridge.core.error.*;
import com.paybridge.core.model.*;
import com.paybridge.spi.*;
import java.math.*;
import java.net.http.*;
import java.time.*;
import java.util.*;

/** bKash URL Checkout adapter: grant token, create, execute, and query. It never handles wallet PIN/OTP. */
public final class BkashPaymentGateway implements PaymentGateway {
  private final BkashConfiguration config; private final HttpClient http; private final ObjectMapper json; private volatile Token token;
  public BkashPaymentGateway(BkashConfiguration config){this(config,HttpClient.newHttpClient(),new ObjectMapper());} BkashPaymentGateway(BkashConfiguration c,HttpClient h,ObjectMapper j){config=c;http=h;json=j;}
  public PaymentProvider provider(){return PaymentProvider.BKASH;} public Set<GatewayCapability> capabilities(){return Set.of(GatewayCapability.CREATE_PAYMENT,GatewayCapability.CONFIRM_PAYMENT,GatewayCapability.GET_PAYMENT,GatewayCapability.HOSTED_CHECKOUT);}
  public Payment createPayment(PaymentRequest r){ObjectNode body=json.createObjectNode(); body.put("mode","0011");body.put("amount",r.amount().amount().toPlainString());body.put("currency",r.amount().currency().getCurrencyCode());body.put("intent","sale");body.put("merchantInvoiceNumber",r.merchantReference());body.put("callbackURL",config.callbackUri().toString()); JsonNode n=post("/tokenized/checkout/create",body,r.idempotencyKey().value()); return payment(n,r.amount(),PaymentStatus.REQUIRES_ACTION);}
  public Payment confirm(PaymentReference r){ObjectNode body=json.createObjectNode().put("paymentID",r.value()); return payment(post("/tokenized/checkout/execute",body,null),null,PaymentStatus.CAPTURED);}
  public Payment getPayment(PaymentReference r){ObjectNode body=json.createObjectNode().put("paymentID",r.value()); return payment(post("/tokenized/checkout/payment/status",body,null),null,PaymentStatus.PENDING);}
  private JsonNode post(String path, JsonNode body,String idempotency){try{HttpRequest.Builder b=HttpRequest.newBuilder(config.baseUri().resolve(path)).header("Content-Type","application/json").header("Accept","application/json").header("Authorization",token().value).header("X-App-Key",config.appKey()); if(idempotency!=null)b.header("X-Idempotency-Key",idempotency); HttpResponse<String> res=http.send(b.POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body))).build(),HttpResponse.BodyHandlers.ofString()); JsonNode n=json.readTree(res.body()); if(res.statusCode()>=400||n.has("errorCode"))throw error(res.statusCode(),n); return n;}catch(PaymentException e){throw e;}catch(Exception e){throw new PaymentException(PaymentErrorCode.NETWORK_ERROR,provider(),null,true,"bKash request failed");}}
  private Token token(){Token current=token;if(current!=null&&current.expires.isAfter(Instant.now().plusSeconds(60)))return current; synchronized(this){if(token!=null&&token.expires.isAfter(Instant.now().plusSeconds(60)))return token;try{ObjectNode b=json.createObjectNode().put("app_key",config.appKey()).put("app_secret",config.appSecret()); HttpRequest req=HttpRequest.newBuilder(config.baseUri().resolve("/tokenized/checkout/token/grant")).header("Content-Type","application/json").header("Accept","application/json").header("username",config.username()).header("password",config.password()).POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(b))).build(); HttpResponse<String> res=http.send(req,HttpResponse.BodyHandlers.ofString());JsonNode n=json.readTree(res.body());if(res.statusCode()>=400||!n.hasNonNull("id_token"))throw error(res.statusCode(),n);return token=new Token(n.get("id_token").asText(),Instant.now().plus(Duration.ofSeconds(n.path("expires_in").asLong(3600))));}catch(PaymentException e){throw e;}catch(Exception e){throw new PaymentException(PaymentErrorCode.NETWORK_ERROR,provider(),null,true,"bKash authentication failed");}}}
  private Payment payment(JsonNode n,Money requestAmount,PaymentStatus fallback){String raw=n.path("transactionStatus").asText(n.path("statusMessage").asText(""));PaymentStatus status="Completed".equalsIgnoreCase(raw)?PaymentStatus.CAPTURED:"Initiated".equalsIgnoreCase(raw)?PaymentStatus.REQUIRES_ACTION:"Cancelled".equalsIgnoreCase(raw)?PaymentStatus.CANCELLED:"Failed".equalsIgnoreCase(raw)?PaymentStatus.FAILED:fallback; Money amount=requestAmount!=null?requestAmount:Money.of(n.path("amount").asText("0"),n.path("currency").asText("BDT"));Map<String,String> meta=new HashMap<>();if(n.hasNonNull("trxID"))meta.put("transaction_id",n.get("trxID").asText());if(!raw.isBlank())meta.put("bkash_status",raw);return new Payment(new PaymentReference(provider(),n.path("paymentID").asText()),status,amount,n.path("bkashURL").asText(null),Instant.now(),meta);}
  private PaymentException error(int s,JsonNode n){String code=n.path("errorCode").asText(null);PaymentErrorCode c=s==401?PaymentErrorCode.AUTHENTICATION_FAILED:s==404?PaymentErrorCode.PAYMENT_NOT_FOUND:s==429?PaymentErrorCode.RATE_LIMITED:s>=500?PaymentErrorCode.PROVIDER_UNAVAILABLE:PaymentErrorCode.INVALID_REQUEST;return new PaymentException(c,provider(),code,s>=500||s==429,"bKash returned an error");} private record Token(String value,Instant expires){}
}
