package com.paybridge.webhooks;
public enum WebhookEventType { PAYMENT_CREATED, PAYMENT_PENDING, PAYMENT_AUTHORIZED, PAYMENT_SUCCEEDED, PAYMENT_FAILED, PAYMENT_CANCELLED, REFUND_CREATED, REFUND_SUCCEEDED, REFUND_FAILED, UNKNOWN }
